export const shopData = {
    showTileData: [],
    invoiceOrder: [
        {
            id: 0,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast 7777',
            author: 'jill111 XXXXX',
            favorite: true,
            amount: 1,
        },
        {
            id: 1,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
            amount: 2,
        },
        {
            id: 2,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
            amount: 10,
        },

    ],


    tilesData: [
        {
            id: 0,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast Test',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 1,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 2,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 3,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 4,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 5,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 6,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 7,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 8,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 9,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 10,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 11,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 12,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 13,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 14,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 15,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 16,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 17,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 18,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 19,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 20,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 21,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 22,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 23,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 24,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 25,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 26,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 27,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 28,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 29,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 30,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 31,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 32,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 33,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 34,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 35,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 36,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 37,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 38,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 39,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 40,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 41,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 42,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 43,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 44,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 45,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 46,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 47,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },

    ]
};