export const shopData = {
    showTileData: [],

    invoiceOrder: [
        {
            id: 0,
            img: '../images/meat/chuck_roast.jpg',
            favorite: true,
            amount: 15,
            sku_name: "Chuck Roast",
            sku_price_show: "1,250/Kg.",
            sku_price: 1250,
            sku_unit: "Kg."
        },
        {
            id: 4,
            img: '../images/meat/wagyu_slice.jpg',
            favorite: true,
            amount: 25,
            sku_name: "Wagyu A5 Slice",
            sku_price_show: "11,850/Kg.",
            sku_price: 11850,
            sku_unit: "Kg."
        },
        {
            id: 5,
            img: '../images/meat/rbeye.jpg',
            favorite: true,
            amount: 15,
            sku_name: "Ribeye Steak",
            sku_price_show: "3,340/Kg.",
            sku_price: 3340,
            sku_unit: "Kg."
        },
        /*{
            id: 6,
            img: '../images/meat/sirloin-steak.jpg',
            favorite: true,
            amount: 15,
            sku_name: "Sirloin Steak",
            sku_price_show: "1,300/Kg.",
            sku_price: 1300,
            sku_unit: "Kg."
        },
        {
            id: 7,
            img: '../images/meat/t_bone_steak.jpg',
            favorite: true,
            amount: 15,
            sku_name: "T-Bone Steak",
            sku_price_show: "2,040/Kg.",
            sku_price: 2040,
            sku_unit: "Kg."
        },
        {
            id: 8,
            img: '../images/meat/beef-ternderloin.jpg',
            favorite: true,
            amount: 15,
            sku_name: "Ternderloin Steak",
            sku_price_show: "3,940/Kg.",
            sku_price: 3940,
            sku_unit: "Kg."
        },
        {
            id: 9,
            img: '../images/meat/top_round_steak.jpg',
            favorite: true,
            amount: 15,
            sku_name: "Top Round Steak",
            sku_price_show: "1,050/Kg.",
            sku_price: 1050,
            sku_unit: "Kg."
        },
        {
            id: 10,
            img: '../images/meat/beef-for-kabobs.jpg',
            favorite: true,
            amount: 15,
            sku_name: "BEEF FOR KABOBS",
            sku_price_show: "750/Kg.",
            sku_price: 750,
            sku_unit: "Kg."
        },*/
    ],

    tilesData: [
        {
            id: 0,
            img: '../images/meat/chuck_roast.jpg',
            favorite: true,
            sku_name: "Chuck Roast",
            sku_price_show: "1,250/Kg.",
            sku_price: 1250,
            sku_unit: "Kg."
        },
        {
            id: 1,
            img: '../images/meat/top_blade_steak.jpg',
            favorite: true,
            sku_name: "Shoulder top blad",
            sku_price_show: "850/Kg.",
            sku_price: 850,
            sku_unit: "Kg."
        },
        {
            id: 2,
            img: '../images/meat/wagyu1.jpg',
            favorite: true,
            sku_name: "Wagyu A5",
            sku_price_show: "9,850/Kg.",
            sku_price: 9850,
            sku_unit: "Kg."
        },
        {
            id: 3,
            img: '../images/meat/wagyu2.jpg',
            favorite: true,
            sku_name: "Wagyu A3",
            sku_price_show: "5,850/Kg.",
            sku_price: 5850,
            sku_unit: "Kg."
        },
        {
            id: 4,
            img: '../images/meat/wagyu_slice.jpg',
            favorite: true,
            sku_name: "Wagyu A5 Slice",
            sku_price_show: "11,850/Kg.",
            sku_price: 11850,
            sku_unit: "Kg."
        },
        {
            id: 5,
            img: '../images/meat/rbeye.jpg',
            favorite: true,
            sku_name: "Ribeye Steak",
            sku_price_show: "3,340/Kg.",
            sku_price: 3340,
            sku_unit: "Kg."
        },
        {
            id: 6,
            img: '../images/meat/sirloin-steak.jpg',
            favorite: true,
            sku_name: "Sirloin Steak",
            sku_price_show: "1,300/Kg.",
            sku_price: 1300,
            sku_unit: "Kg."
        },
        {
            id: 7,
            img: '../images/meat/t_bone_steak.jpg',
            favorite: true,
            sku_name: "T-Bone Steak",
            sku_price_show: "2,040/Kg.",
            sku_price: 2040,
            sku_unit: "Kg."
        },
        {
            id: 8,
            img: '../images/meat/beef-ternderloin.jpg',
            favorite: true,
            sku_name: "Ternderloin Steak",
            sku_price_show: "3,940/Kg.",
            sku_price: 3940,
            sku_unit: "Kg."
        },
        {
            id: 9,
            img: '../images/meat/top_round_steak.jpg',
            favorite: true,
            sku_name: "Top Round Steak",
            sku_price_show: "1,050/Kg.",
            sku_price: 1050,
            sku_unit: "Kg."
        },
        {
            id: 10,
            img: '../images/meat/beef-for-kabobs.jpg',
            favorite: true,
            sku_name: "BEEF FOR KABOBS",
            sku_price_show: "750/Kg.",
            sku_price: 750,
            sku_unit: "Kg."
        },
        {
            id: 11,
            img: '../images/meat/chuck_roast.jpg',
            favorite: false,
            sku_name: "Chuck Roast",
            sku_price_show: "1,250/Kg.",
            sku_price: 1250,
            sku_unit: "Kg."
        },
        {
            id: 12,
            img: '../images/meat/top_blade_steak.jpg',
            favorite: false,
            sku_name: "Shoulder top blad",
            sku_price_show: "850/Kg.",
            sku_price: 850,
            sku_unit: "Kg."
        },
        {
            id: 13,
            img: '../images/meat/wagyu1.jpg',
            favorite: false,
            sku_name: "Wagyu A5",
            sku_price_show: "9,850/Kg.",
            sku_price: 9850,
            sku_unit: "Kg."
        },
        {
            id: 14,
            img: '../images/meat/wagyu2.jpg',
            favorite: false,
            sku_name: "Wagyu A3",
            sku_price_show: "5,850/Kg.",
            sku_price: 5850,
            sku_unit: "Kg."
        },
        {
            id: 15,
            img: '../images/meat/wagyu_slice.jpg',
            favorite: false,
            sku_name: "Wagyu A5 Slice",
            sku_price_show: "11,850/Kg.",
            sku_price: 11850,
            sku_unit: "Kg."
        },
        {
            id: 16,
            img: '../images/meat/rbeye.jpg',
            favorite: false,
            sku_name: "Ribeye Steak",
            sku_price_show: "3,340/Kg.",
            sku_price: 3340,
            sku_unit: "Kg."
        },
        {
            id: 17,
            img: '../images/meat/sirloin-steak.jpg',
            favorite: false,
            sku_name: "Sirloin Steak",
            sku_price_show: "1,300/Kg.",
            sku_price: 1300,
            sku_unit: "Kg."
        },
        {
            id: 18,
            img: '../images/meat/t_bone_steak.jpg',
            favorite: false,
            sku_name: "T-Bone Steak",
            sku_price_show: "2,040/Kg.",
            sku_price: 2040,
            sku_unit: "Kg."
        },
        {
            id: 19,
            img: '../images/meat/beef-ternderloin.jpg',
            favorite: false,
            sku_name: "Ternderloin Steak",
            sku_price_show: "3,940/Kg.",
            sku_price: 3940,
            sku_unit: "Kg."
        },
        {
            id: 20,
            img: '../images/meat/top_round_steak.jpg',
            favorite: false,
            sku_name: "Top Round Steak",
            sku_price_show: "1,050/Kg.",
            sku_price: 1050,
            sku_unit: "Kg."
        },
        {
            id: 21,
            img: '../images/meat/beef-for-kabobs.jpg',
            favorite: false,
            sku_name: "BEEF FOR KABOBS",
            sku_price_show: "750/Kg.",
            sku_price: 7750,
            sku_unit: "Kg."
        },
    ],

    invoiceOrder_xxx: [
        {
            id: 0,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast 7777',
            author: 'jill111 XXXXX',
            favorite: true,
            amount: 19,
        },
        {
            id: 1,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
            amount: 298,
        },
        {
            id: 2,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
            amount: 100,
        },

    ],

    tilesData_xxx: [
        {
            id: 0,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast Test',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 1,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 2,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 3,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 4,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 5,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 6,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 7,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 8,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 9,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 10,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 11,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 12,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 13,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 14,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 15,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 16,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 17,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 18,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 19,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 20,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 21,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 22,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 23,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 24,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 25,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 26,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 27,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 28,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 29,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 30,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 31,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 32,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 33,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 34,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 35,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 36,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 37,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 38,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 39,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },
        {
            id: 40,
            img: '../images/grid-list/00-52-29-429_640.jpg',
            title: 'Breakfast',
            author: 'jill111',
            favorite: true,
        },
        {
            id: 41,
            img: '../images/grid-list/burger-827309_640.jpg',
            title: 'Tasty burger',
            author: 'pashminu',
            favorite: true,
        },
        {
            id: 42,
            img: '../images/grid-list/camera-813814_640.jpg',
            title: 'Camera',
            author: 'Danson67',
            favorite: false,
        },
        {
            id: 43,
            img: '../images/grid-list/morning-819362_640.jpg',
            title: 'Morning',
            author: 'fancycrave1',
            favorite: true,
        },
        {
            id: 44,
            img: '../images/grid-list/hats-829509_640.jpg',
            title: 'Hats',
            author: 'Hans',
            favorite: false,
        },
        {
            id: 45,
            img: '../images/grid-list/honey-823614_640.jpg',
            title: 'Honey',
            author: 'fancycravel',
            favorite: false,
        },
        {
            id: 46,
            img: '../images/grid-list/vegetables-790022_640.jpg',
            title: 'Vegetables',
            author: 'jill111',
            favorite: false,
        },
        {
            id: 47,
            img: '../images/grid-list/water-plant-821293_640.jpg',
            title: 'Water plant',
            author: 'BkrmadtyaKarki',
            favorite: false,
        },

    ],
    orderObj: '',

    orderNumbers: [
        {
            id: 0,
            orderNumber: 'ORDER20170519',
            createBy: 'Phanumas S.',
            lastUpdate: '2017-05-17',
            orderStatus: 'port',
            amount: 19,
        },
        {
            id: 1,
            orderNumber: 'ORDER20170518',
            createBy: 'Adam L.',
            lastUpdate: '2017-05-10',
            orderStatus: 'port',
            amount: 10,
        },
        {
            id: 2,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'port',
            amount: 9,
        },
        {
            id: 3,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'shipping',
            amount: 9,
        },
        {
            id: 4,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'shipping',
            amount: 9,
        },
        {
            id: 5,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'shipping',
            amount: 9,
        },
        {
            id: 6,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'confirm',
            amount: 9,
        },
        {
            id: 7,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'confirm',
            amount: 9,
        },
        {
            id: 8,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'confirm',
            amount: 9,
        },
        {
            id: 9,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'confirm',
            amount: 9,
        },
        {
            id: 10,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'confirm',
            amount: 9,
        },
        {
            id: 11,
            orderNumber: 'ORDER20170517',
            createBy: 'Taylor S.',
            lastUpdate: '2017-05-11',
            orderStatus: 'confirm',
            amount: 9,
        },


    ]
};